### ISSUE TITLE
Error: SubtleCrypto not available!

### ISSUE THREAD

**Issue by dogukanakkaya** [ArweaveTeam/arweave-js#160]
Getting static export errors with Next.js (Node version 18.2.0) since last release 3 days ago. I saw some crypto related merges by @hlolli maybe these are causing the problem, not sure?

```
Error: SubtleCrypto not available!
    at new WebCryptoDriver (*/node_modules/arweave/web/lib/crypto/webcrypto-driver.js:10:19)
    at Object.<anonymous> (*/node_modules/arweave/web/common.js:120:18)
```

**Comment by hlolli** [comment]
it's most likely from https://github.com/Bundlr-Network/arbundles/pull/50 ?
Use lower semantic version until arbundles merge the fix. The error is obvious here, a browser based code is being called in nodejs environment. Since arweave-js has seperate entry for nodejs (main) and web (browser) in package.json, webpack will be clever enough to pick correct entry for nextjs.

**Comment by atob1** [comment]
I'm having the same issue; how'd you work around it?

**Comment by hlolli** [comment]
use "1.10.22" until arbundles is fixed

**Comment by atob1** [comment]
Hm I'm still having the issue when downgrading arweave to this version.

**Comment by hlolli** [comment]
This should be fixed now in arbundles, try adding this to package.json if you're using yarn

```json
  "resolutions": {
    "**/arbundles": "^0.6.19"
  }
```

**Comment by dogukanakkaya** [comment]
Adding `resolutions` did not work for me, still getting the same error (using npm instead of yarn btw).
